# Site settings
title: Dengni8023
SEOTitle: Dengni8023的博客 | Dengni8023 Blog
header-img: img/default-header.jpg
email: 945835664@qq.com
description: "Know more. Do more. Be more."
keyword: "等你8023, Dengni8023, Jigao, 继高, iOS, Apple, iPhone"
url: "http://dengni8023.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/dengni8023/dengni8023.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "虚心学习，执行至上，成就更好的自己。"
sidebar-avatar: /img/avatar-dengni8023.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
#RSS: false # RSS阅读器
#weibo_username:     username
#zhihu_username:     username
github_username:    dengni8023
#facebook_username:  username
#jianshu_username:   jianshu_id
#twitter_username:   username




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Plugins
# support local preview for Jekyll 3.7
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: dengni8023

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 909974e5f12ca3bb6b01   #生成的clientID
  clientSecret: 4f209521b270df4c36b806b01e269b002d9dccef  #同上
  repo: dengni8023.github.io    #仓库名称
  owner: dengni8023    #github用户名
  admin: dengni8023
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Apple",
        href: "https://apple.com"
    },
    {
        title: "Apple Dev",
        href: "https://developer.apple.com/"
    }
]
